### ISSUE TITLE
Proofread: Changing presets and overriding markup on Stackable

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/tickets#5]
**Ticket Details**
- Ticket URL: https://wordpress.org/support/topic/possible-to-change-defaults-on-blocks/
- Ticket receipt date: January. 29, 2018

**What's the question?**

**Original Message:**
Hi there,

Hoping to use Stackable on a production site but we were wondering:

1. Is it possible to either change the style defaults or disable the controls for certain users or roles? For example, most of Stackable’s elements have a border radius of 12px. We’d like to either change this default or disable the option completely so a user on the site can’t inadvertently change the styling in a way that doesn’t match what was predetermined.

2. Also, is it possible to change or override the markup produced by Stackable blocks in anyway? For example, if we want to add a card but there is a special class included in the output rather than simply adding said class via the ‘Advanced’ editing option, is that possible?

Thanks in advance for your help.

**Reply:**
About your questions:

1. It's currently not possible to set a user group accessibility with blocks. Also, the blocks will always have the preset settings when added. If you want to create your own preset with blocks, you can still create a Reusable Block from the blocks you've recently created. The setting will be available in the Options menu bar > Add to Reusable Blocks.

2. This is possible by editing the block as HTML. It's also available in the Options menu bar. Please note that once you override block contents, the Block Editor will convert it into HTML and you need to Edit Visually (also available via options) if you want to see the block again. 

Hope this helps! 🙂

**Comment by bfintal** [comment]
@Gambit-Alyssa some comments about your reply:

> 1. It's currently not possible to set a user group accessibility with blocks. Also, the blocks will always have the preset settings when added. If you want to create your own preset with blocks, you can still create a Reusable Block from the blocks you've recently created. The setting will be available in the Options menu bar > Add to Reusable Blocks.

This is wrong. He isn't talking about reusable blocks, he is talking about disabling inspector options depending on who's using the editor.

My answer:

It's currently not possible to set different style defaults or option availability for different users/roles.

> 2. This is possible by editing the block as HTML. It's also available in the Options menu bar. Please note that once you override block contents, the Block Editor will convert it into HTML and you need to Edit Visually (also available via options) if you want to see the block again.

This is wrong also. He is talking about whether or not he can automatically add a `class` to the block every time it is used.

My answer:

This isn't possible also in Stackable without modifying how blocks are registered to the block editor. However, the block editor has a `blocks.registerBlockType` JS filter that fires right before blocks are registered. You can use that to override some of the block's settings. There's also a `blocks.getBlockDefaultClassName` filter that can be used to change the classNames generated for the blocks.
